Initial draft
DigitalBackstage/orange-juicer pull request #1
Opened 2017-01-16 17:04 UTC by greg0ire

2017-01-16 17:19 UTC, greg0ire commented on src/MetadataProvider/MediaInfoProvider.php
> +         * https://github.com/mhor/php-mediainfo/issues/65 is fixed */
Do not merge yet, this has been fixed and released :)

2017-01-24 15:07 UTC, L-P requested changes

2017-01-24 15:07 UTC, L-P commented on Makefile
> +	@ cp $@.dist $@
-@

2017-01-24 15:07 UTC, L-P commented on composer.json
> +    "license": "proprietary",
Nope.

2017-01-24 15:07 UTC, L-P commented on docker/docker-compose.override.yml
> +      - ~/Vidéos:/data
Specific to your setup

2017-01-24 15:07 UTC, L-P commented on spec/ManifestGeneratorSpec.php
> +            array()
PHP 5.4 is long gone, `[]`

2017-01-24 15:07 UTC, L-P commented on src/ManifestGenerator.php
> +        $metadata['multi_format_set']
Confusing indentation

2017-01-24 15:07 UTC, L-P commented on src/TrailerDetector.php
> +            '|MPEG\d+\.\mpg|',
`\m` ?

2017-01-24 16:27 UTC, L-P approved these changes

2017-01-24 16:28 UTC, merged